### ISSUE TITLE
Error: Invalid type for 'value' (must be a byte string)

### ISSUE THREAD

**Issue by jporcelg** [mpetazzoni/kazoocli#3]
Unable to create or set new entries
```
Error: Invalid type for 'value' (must be a byte string)
```
example
```
/> set test test
Error: Invalid type for 'value' (must be a byte string)
```
Using: 
   macOS 10.13.3
   python 2.7.13
   latest kazoocli available via pip (1.0)
   docker zookeeper-3.4.12

**Comment by mpetazzoni** [comment]
@jporcelg Thanks for the report! What version of kazoocli are you using? I recently made changes to help make Kazoocli work with Python3, but maybe I broke something for Python 2.7 in the process?

**Comment by jporcelg** [comment]
from site-packages and pip I can see
```
kazoocli (1.0)
```
other dependencies
```
hexdump (3.3)
kazoo (2.4.0)
pytz (2016.4)
six (1.11.0)
```

**Comment by mpetazzoni** [comment]
Could you try with the latest from master after upgrading with:

```
pip install --upgrade git+https://github.com/mpetazzoni/kazoocli
```

I've just pushed a few fixes. I was able to `set` / `get` with both Python 2.7 and Python 3.6.

**Comment by jporcelg** [comment]
@mpetazzoni it does actually work now
```
/> set test test
created : Thu Jun  7 17:40:08 2018 UTC
modified: Fri Jun 15 17:14:27 2018 UTC
children: 1
  data    : 4 bytes

/> cat test
test
```

thanks for the fix!

**Comment by mpetazzoni** [comment]
Awesome, thanks!
